### ISSUE TITLE
Los iframes de Google docs (programa y tutoriales) son bloqueados en ciertos sistemas

### ISSUE THREAD

**Issue by mpaulacaldas** [rdaymedellin/rdaymedellin.github.io#1]
Hola! La página de "Programa" y "Tutoriales" me aparecen vacias:

![image](https://github.com/rday-colombia/2023/assets/33395215/ab28dac4-56dc-43e7-981d-e5fed96d59ac)

Después de un poco de investigación, me di cuenta que estas son bloqueados por las reglas de firewall de mi trabajo, que prohíbe todos los productos de Google docs. Esta restricción es bastante común en las firewall corporativas, entonces podría estar afectando a varias personas. Les sugeriría poner la información directamente en la página (podrían usar un chunk que la hoja de cálculo con `googlesheets4`), o agregar una frase para indicar que la información se encuentra en Google sheets 😄

**Comment by fhernanb** [comment]
**Muchas gracias** por avisarnos. Ya hicimos el cambio a imágenes:

https://rday-colombia.github.io/2023/tutoriales.html

**Comment by mpaulacaldas** [comment]
Me aparece todo perfecto! Cierro el issue entonces. Mucha suerte en el evento!
